### ISSUE TITLE
Seems to not run on Jekyll 3.3.1

### ISSUE THREAD

**Issue by tsangiotis** [juusaw/amp-jekyll#20]
I put the required files in the specified positions and specified `ampdir: amp` on my `_config.yml`.

Next I ran `bundle exec jekyll serve` on my jekyll directory and the site serves fine but a `_site/amp` directory is not being generated.

I saw #2 and tried serving without the plugins but got no different results.

**Comment by juusaw** [comment]
Hi!

I don't think the problem has to do with Jekyll version. I personally generate my site with 3.4.0 and previously used 3.3.X (can't recall the minor version).

Have you added the file `amp.html` to the `_layouts` folder? Do you get any errors logged when running `jekyll serve` or `jekyll build`?

If your site's source code is public, I could try to locate the problem directly. Otherwise you could try adding some print logging to the Ruby files to see if the code actually gets executed.

**Comment by wiseindy** [comment]
Hi juusaw,

I have the same problem with my site. I've saved the `amp.html` file to the `layouts` folder and also have specified my `ampdir` in `_config.yml`. However, when I generate my site by running `bundle exec jekyll serve`, the `ampdir` doesn't get created in `_site`.

I do not see any errors during build or serve. Also, I'm not really familiar with ruby so I am unable to debug.

My site's source code is public and you can find it here: [Source](https://github.com/wiseindy/wiseindy.github.io)

**Comment by wiseindy** [comment]
I've figured out my problem. All my posts had a `permalink: /somewhere` in the front matter. If I remove the permalink, the `ampdir` directory is created.

`amp-jekyll` plugin seems to ignore posts with a `permalink`. This issue is referenced here: https://github.com/juusaw/amp-jekyll/issues/27

**Comment by juusaw** [comment]
I'll close this one as issue #27 addresses the same problem.
