### ISSUE TITLE
Alternative to fastimage to build locally

### ISSUE THREAD

**Issue by mrowdy** [juusaw/amp-jekyll#6]
A lot of jekyll sites are hosted with github pages which means they are built once with `jekyll build` 

Since fastimage's purpose is to fetch images over the web and the jekyll page is built local on the serve this won't work. 

I'm not a ruby developer but i think [RMagick](https://rubygems.org/gems/rmagick/versions/2.15.4) would to the trick. I'm aware that RMagick needs ImageMagick installed but in my opinion it is better to install something like ImageMagick than being not able to serve images.

**Comment by mrowdy** [comment]
Looks like i didn't thought this through. It's not possible to install anything with jekyll gh-pages

**Comment by juusaw** [comment]
I don't think ImageMagick would solve the problem at hand. Fastimage works with local files too, the problem is that the files don't exist in the `_site` folder at the time the plugin code is executed. The `--skip-initial-build` flag and building afterwards trick works just file for me. If a way to build local files without the workaround is found, that would be awesome.
